name: Deploy Client Workflow

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
  workflow_dispatch:
    inputs:
      name:
        description: "Mannual dispatch"
        required: true
        default: "deploy"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"

      - name: Install Dependencies
        working-directory: ./client
        run: npm ci

      - name: Build
        working-directory: ./client
        run: npm run build
        env:
          CI: ""

      # - name: Deploy
      #   run: |
      #     npm install -g gh-pages
      #     npx gh-pages -d './client/build'
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ./client/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
